### ISSUE TITLE
Indryk overløb i digtvers

### ISSUE THREAD

**Issue by thabz** [thabz/Kalliope#146]
Kan vi få anden-linjen i en ombrudt verslinje (pga. smal skærm) til enten at være højrestillet eller indrykket fra venstre.

Forsøg at lave en ny \<div> `c` i den eksisterende.

```css
c {
   margin: 40px;
}
c::first-line {
   margin: -40px;
}
```
