### ISSUE TITLE
Forklaringstegn ↄ

### ISSUE THREAD

**Issue by thabz** [thabz/Kalliope#877]
Vi bruger Unicode ↄ (reverse c) eller ↄ (open o) overalt i Kalliope som [forklaringstegnet](http://www.typografi.org/forklaringstegn/forklaringstegn.html), men det ville være historien, typografisk og æstetisk mere  korrekt at vende et ægte c på hovedet. Dette kan gøres med css:

```css
.flip {
  display: inline-block;
  transform: rotateY(180deg);
}
```

Fore eksempel (<span>cc</span)...
